version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      timezone: 'Europe/Warsaw'
      day: 'saturday'
      time: '06:00'
    target-branch: 'main'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'ci'
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      timezone: 'Europe/Warsaw'
      day: 'saturday'
      time: '06:00'
    target-branch: 'main'
    open-pull-requests-limit: 20
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
